[package]
name = "raw_serde_derive"
version = "0.1.2"
authors = ["Joshua Karns <jkarns275@gmail.com>"]
license = "MIT"
description = "Automatically derives the RawSerialize and RawDeserialize traits for raw_serde"
[lib]
proc-macro = true

[dependencies]
syn = "0.10.5"
quote = "0.3.10"
